import { Link } from 'react-router-dom'

export default function PrivacyPage() {
  return (
    <div className="legal-page">
      <nav style={{ position: 'absolute', top: 20, left: 40, right: 40, display: 'flex', justifyContent: 'space-between' }}>
        <Link to="/" style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 20, fontWeight: 800, color: 'var(--text)' }}>
          <div style={{ width: 32, height: 32, background: 'linear-gradient(135deg, #6366f1, #8b5cf6)', borderRadius: 8, display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white', fontWeight: 800, fontSize: 11 }}>CP</div>
          CareerPilot
        </Link>
        <Link to="/login" className="btn btn-primary btn-sm">Sign In</Link>
      </nav>

      <div className="legal-content">
        <h1>Privacy Policy</h1>
        <p className="legal-updated">Last updated: April 9, 2026</p>

        <p>
          CareerPilot ("we", "our", "us") is committed to protecting the privacy of our users ("you", "your").
          This Privacy Policy explains how we collect, use, store, and share your personal information when
          you use the CareerPilot web application and services.
        </p>

        <h2>1. Information We Collect</h2>

        <h3>Account Information</h3>
        <ul>
          <li>Email address (required for account creation)</li>
          <li>Name and profile photo (if you sign in with Google)</li>
          <li>Password hash (if you use email/password sign-in; we never store plaintext passwords)</li>
        </ul>

        <h3>Resume and Career Data</h3>
        <ul>
          <li>Resume text that you upload or paste</li>
          <li>Job descriptions that you provide</li>
          <li>Tailored resumes, cover letters, and match analyses generated by the service</li>
          <li>Interview prep questions and responses</li>
          <li>LinkedIn optimization suggestions</li>
          <li>Application tracking data (company names, roles, statuses, notes)</li>
        </ul>

        <h3>Payment Information</h3>
        <ul>
          <li>Payment processing is handled entirely by Stripe. We do not store credit card numbers, CVVs, or full card details on our servers.</li>
          <li>We store your Stripe customer ID and subscription status to manage your account.</li>
        </ul>

        <h3>Usage Data</h3>
        <ul>
          <li>Number of tailoring requests per month (for free tier limits)</li>
          <li>Timestamps of actions taken within the app</li>
        </ul>

        <h2>2. How We Use Your Information</h2>
        <ul>
          <li><strong>Provide the service:</strong> Your resume and job description text are sent to our AI provider (Anthropic) to generate tailored resumes, cover letters, match scores, interview prep questions, and LinkedIn suggestions.</li>
          <li><strong>Account management:</strong> Your email is used for authentication and account recovery.</li>
          <li><strong>Billing:</strong> Subscription and payment data is used to manage your plan and access level.</li>
          <li><strong>Service improvement:</strong> Aggregated, anonymized usage statistics may be used to improve the product.</li>
        </ul>

        <h2>3. Third-Party Services</h2>
        <p>We use the following third-party services that process your data:</p>
        <table>
          <thead>
            <tr><th>Service</th><th>Purpose</th><th>Data Shared</th></tr>
          </thead>
          <tbody>
            <tr><td>Google Firebase</td><td>Authentication and database</td><td>Email, account data, app data</td></tr>
            <tr><td>Anthropic (Claude API)</td><td>AI-powered resume tailoring</td><td>Resume text, job descriptions</td></tr>
            <tr><td>Stripe</td><td>Payment processing</td><td>Email, payment details</td></tr>
            <tr><td>Render</td><td>Backend hosting</td><td>API requests (encrypted in transit)</td></tr>
          </tbody>
        </table>
        <p>Each third-party service operates under its own privacy policy. We encourage you to review them.</p>

        <h2>4. Data Storage and Security</h2>
        <ul>
          <li>All data is stored in Google Cloud Firestore with per-user access controls. Users can only access their own data.</li>
          <li>All data in transit is encrypted via HTTPS/TLS.</li>
          <li>Authentication is handled by Firebase Auth with industry-standard security practices.</li>
          <li>We do not sell, rent, or trade your personal information to third parties.</li>
        </ul>

        <h2>5. Data Retention</h2>
        <ul>
          <li><strong>Active accounts:</strong> Your data is retained for as long as your account is active.</li>
          <li><strong>Account deletion:</strong> When you delete your account, all personal data (resumes, cover letters, tailoring history, application data, and subscription records) is permanently deleted within 30 days.</li>
          <li><strong>Inactive accounts:</strong> Accounts with no activity for 12 months may be flagged for deletion. You will be notified via email before any data is removed.</li>
          <li><strong>AI processing:</strong> Resume and job description text sent to Anthropic's API is processed in real-time and is subject to Anthropic's data retention policy. CareerPilot does not control Anthropic's data practices — see <a href="https://www.anthropic.com/privacy" target="_blank" rel="noopener noreferrer">Anthropic's Privacy Policy</a>.</li>
        </ul>

        <h2>6. Your Rights (GDPR and Global Privacy)</h2>
        <p>Regardless of where you are located, you have the following rights:</p>
        <ul>
          <li><strong>Right to access:</strong> Request a copy of all personal data we hold about you.</li>
          <li><strong>Right to rectification:</strong> Update or correct your personal data.</li>
          <li><strong>Right to deletion:</strong> Delete your account and all associated data at any time from your account settings.</li>
          <li><strong>Right to data portability:</strong> Request your data in a machine-readable format.</li>
          <li><strong>Right to restrict processing:</strong> Ask us to stop processing your data while a complaint is resolved.</li>
          <li><strong>Right to object:</strong> Object to data processing based on legitimate interest.</li>
        </ul>
        <p>
          To exercise any of these rights, use the "Delete Account" option in the app sidebar,
          or contact us at the email below.
        </p>

        <h2>7. Cookies</h2>
        <p>
          CareerPilot uses only essential cookies and local storage for authentication (Firebase Auth session tokens).
          We do not use advertising cookies, analytics trackers, or third-party tracking pixels.
        </p>

        <h2>8. Children's Privacy</h2>
        <p>
          CareerPilot is not intended for use by anyone under the age of 16. We do not knowingly
          collect personal data from children.
        </p>

        <h2>9. Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy from time to time. Changes will be posted on this page
          with an updated "Last updated" date. Continued use of the service after changes constitutes
          acceptance of the updated policy.
        </p>

        <h2>10. Contact</h2>
        <p>
          If you have questions about this Privacy Policy or wish to exercise your data rights, contact us at:
        </p>
        <p><strong>Email:</strong> privacy@careerpilot.app</p>

        <div className="legal-footer">
          <Link to="/terms">Terms of Service</Link>
          <Link to="/">Back to Home</Link>
        </div>
      </div>
    </div>
  )
}
